### PR TITLE
Improve legacy NVIDIA / Quadro compatibility

### PR DESCRIPTION
**Pull request by 1larity**
## Summary
This is the isolated Quadro / legacy NVIDIA compatibility slice split out from the broader PR-808 work.

Scope is intentionally limited to legacy CUDA / pre-Ampere compatibility and the startup paths needed to support it.
Partially address #486, #149, #245
## Included
- launcher probe for unsupported CUDA arch wheels and automatic legacy CUDA 12.1 torch fallback
- pre-Ampere CUDA dtype fallback to float16 instead of bfloat16
- pre-Ampere quantization defaulting to `w8a8_dynamic`
- CUDA bool-argsort workaround during model init for older driver/runtime combinations
- focused downloader fix so partial checkpoint directories do not suppress required model downloads
- focused tests for launcher, init-service, quantization-selection, and downloader behavior

## Validation
Automated:
- `uv run python -m unittest acestep.cli_args_test`
- `uv run python -m unittest acestep.launcher_compat_test acestep.launcher_legacy_torch_fix_test`
- `uv run python -m unittest acestep.model_downloader_test`
- `uv run python -m unittest acestep.core.generation.handler.init_service_test.InitServiceMixinTests`
- `uv run python -m unittest acestep.ui.gradio.events.generation.service_init_quantization_test`
- `uv run python -m unittest acestep.ui.gradio.events.generation.service_init_device_test`

Manual:
- load and generation tested on Quadro P1000 hardware
- load and generation tested on RTX 3060 Ti, 2070 Super

## Notes
- This PR does not include the broader PR-808 UI/API/training changes.
- Quantization is intentionally allowed without forcing `torch.compile`; that behavior is covered by tests on this branch.

## Summary by CodeRabbit

* **New Features**
  * Expanded quantization options with auto-detection and UI selection; legacy NVIDIA GPU compatibility probes added to startup/install flows.

* **Improvements**
  * Smarter GPU/device detection and dtype selection (bfloat16 when supported); quantization no longer forces compilation; model existence checks now validate presence of weight artifacts.

* **Tests**
  * Broadened test coverage for quantization parsing/selection, GPU compatibility probes, device resolution, model presence, and startup behaviors.

### CODE REVIEW

File: acestep/gpu_config.py [hunk 1]
```diff
@@ -105,6 +105,49 @@ def is_rocm_available() -> bool:
...
+
+def cuda_prefers_w8a8_dynamic_quantization() -> bool:
+    """Return whether the active CUDA device should prefer w8a8 dynamic quantization."""
+    try:
+        import torch
+
+        if not torch.cuda.is_available():
+            return False
+        major, _ = torch.cuda.get_device_capability()
+        return major < 7
```
[the remark this answers is not in the document]
Comment (1larity) [reply acestep/gpu_config.py]: I did not take the `major < 8` change in this PR intentionally.

This branch is scoped to the Quadro / legacy NVIDIA compatibility slice I was able to validate, and the current quantization fallback remains `compute capability < 7`, which matches the behavior implemented and tested here. Expanding that to all pre-Ampere GPUs would change runtime behavior for Volta/Turing as well, and I do not currently have Volta hardware available to validate that broader fallback safely.

Given the PR scope and available test coverage, I kept the narrower `< 7` threshold to avoid widening behavior beyond the hardware combinations we were able to exercise.

File: acestep/ui/gradio/events/generation/service_init_quantization_test.py [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+        with patch("torch.cuda.is_available", return_value=True), patch(
+            "torch.cuda.get_device_capability", return_value=(6, 1)
+        ):
+            self.assertEqual(
+                module._select_quantization_value(
+                    quantization_enabled=True,
+                    device="cuda",
+                ),
+                "w8a8_dynamic",
+            )
```
[the remark this answers is not in the document]
Comment (1larity) [reply acestep/ui/gradio/events/generation/service_init_quantization_test.py]: I checked this against the current branch state. The UI path now delegates to the shared `gpu_config.cuda_prefers_w8a8_dynamic_quantization()` helper, and that helper still intentionally uses the narrower `compute capability < 7` threshold on this PR.

So I did not add the suggested 7.x regression test, because it would assert behavior this branch does not implement. Expanding the fallback to cover Volta/Turing as well would broaden runtime behavior beyond the hardware combinations I was able to validate for this PR.

File: start_api_server.bat [hunk 3]
```diff
@@ -279,12 +285,12 @@ if exist "%~dp0python_embedded\python.exe" (
...
     if not "%LM_MODEL_PATH%"=="" set "ACESTEP_ARGS=!ACESTEP_ARGS! %LM_MODEL_PATH%"
 
-    uv run !ACESTEP_ARGS!
+    uv run --no-sync !ACESTEP_ARGS!
     if !ERRORLEVEL! NEQ 0 (
         echo.
         echo [Retry] Online dependency resolution failed, retrying in offline mode...
         echo.
-        uv run --offline !ACESTEP_ARGS!
+        uv run --offline --no-sync !ACESTEP_ARGS!
```
[the remark this answers is not in the document]
Comment (1larity) [reply start_api_server.bat]: The success-path exit behavior has been corrected in the latest push, but I intentionally kept `uv run --no-sync` here.

On this PR, the Windows launcher may replace the default torch build with a legacy-compatible CUDA 12.1 torch install for unsupported pre-Ampere/Quadro hardware. If the subsequent launch path uses plain `uv run`, `uv` can immediately resync the environment back to the locked/default torch build and undo that compatibility fix before startup completes.

So this branch keeps `--no-sync` on the primary Windows launch path deliberately to preserve the launcher-applied legacy torch compatibility change. The offline retry path remains unchanged as well.

File: start_gradio_ui.bat [hunk 4]
```diff
@@ -314,12 +320,12 @@ if exist "%~dp0python_embedded\python.exe" (
...
     if not "%AUTH_PASSWORD%"=="" set "ACESTEP_ARGS=!ACESTEP_ARGS! %AUTH_PASSWORD%"
 
-    uv run !ACESTEP_ARGS!
+    uv run --no-sync !ACESTEP_ARGS!
     if !ERRORLEVEL! NEQ 0 (
         echo.
         echo [Retry] Online dependency resolution failed, retrying in offline mode...
         echo.
-        uv run --offline !ACESTEP_ARGS!
+        uv run --offline --no-sync !ACESTEP_ARGS!
```
[the remark this answers is not in the document]
Comment (1larity) [reply start_gradio_ui.bat]: The success-path exit behavior has been corrected in the latest push, but I intentionally kept `uv run --no-sync` here.

On this PR, the Windows launcher may replace the default torch build with a legacy-compatible CUDA 12.1 torch install for unsupported pre-Ampere/Quadro hardware. If the subsequent launch path uses plain `uv run`, `uv` can immediately resync the environment back to the locked/default torch build and undo that compatibility fix before startup completes.

So this branch keeps `--no-sync` on the primary Windows launch path deliberately to preserve the launcher-applied legacy torch compatibility change. The offline retry path remains unchanged as well.
