### ISSUE TITLE
Lora Training: error on folder scan

### ISSUE THREAD

**Issue by ItsGeneralButtNaked** [ace-step/ACE-Step-1.5#283]
After loading audio folder location and hitting Scan I see the following error:

Failed to get duration for test.mp3: module 'torchaudio' has no attribute 'info'

Environment
OS: Linux Mint (Ubuntu-based)
Python: 3.10+ (managed by uv)
Torch: 2.10.0+cu128
Torchaudio: 2.10.0+cu128
TorchAudio Version: 0.15.0
Install method: uv install / uv run

I had just recently run a git pull and uv sync after the gradio ui updates today.

Fixed with llm:

Replace the current get_audio_duration() in audio_io.py:

def get_audio_duration(audio_path: str) -> int:
    try:
        info = torchaudio.info(audio_path)
        return int(info.num_frames / info.sample_rate)
    except Exception as e:
        logger.warning(f"Failed to get duration for {audio_path}: {e}")
        return 0

With a version that works on torchaudio 2.0 → 2.10+:

def get_audio_duration(audio_path: str) -> int:
    try:
        waveform, sample_rate = torchaudio.load(audio_path)
        return int(waveform.shape[-1] / sample_rate)
    except Exception as e:
        logger.warning(f"Failed to get duration for {audio_path}: {e}")
        return 0

No error after the clankers propsed amendment

**Comment by Helikaon23s** [comment]
Mine all went pear shaped after updating today, nothing works for training for me. Had to use an install from yesterday instead.

**Comment by ItsGeneralButtNaked** [comment]
> Mine all went pear shaped after updating today, nothing works for training for me. Had to use an install from yesterday instead.

Its my first time trying the training. A few steps later my ancient PC was taking ages on the preprocessing and there was nothing showing in the terminal, not sure if thats broken or just stalling due to old hardware. I cancelled out due to no progress indicator, will have another go later.

**Comment by DarkAlchy** [comment]
Same for me.  I tried to redo yesterday's training to make the latents and 10m it still had not done anything.  It just sat there in the cli, unlike yesterday which was almost instantaneous.

**Comment by Vedant-CTOI** [comment]
Can you please help me understand how you provide the path to your audio directory within Gradio?

**Comment by ItsGeneralButtNaked** [comment]
> Can you please help me understand how you provide the path to your audio directory within Gradio?

Make a new folder in the project directory (you'll see an error otherwise) and then copy paste that folder path into the gradio ui

**Comment by Vedant-CTOI** [comment]
> > Can you please help me understand how you provide the path to your audio directory within Gradio?
> 
> Make a new folder in the project directory (you'll see an error otherwise) and then copy paste that folder path into the gradio ui

Thanks. I can see my question is silly, but where to make this new folder? Inside Ace Step 1.5 root folder? I have tried to place in multiple locations, but the path is not being accepted. Thanks in advance.

**Comment by ItsGeneralButtNaked** [comment]
> > > Can you please help me understand how you provide the path to your audio directory within Gradio?
> > 
> > 
> > Make a new folder in the project directory (you'll see an error otherwise) and then copy paste that folder path into the gradio ui
> 
> Thanks. I can see my question is silly, but where to make this new folder? Inside Ace Step 1.5 root folder? I have tried to place in multiple locations, but the path is not being accepted. Thanks in advance.

There's no silly questions with projects like these ha. Yes, I just made a folder in the AceStep root folder as when I tried to pull tracks from another drive I got an error in the terminal. 

Are you sure its the path not being accepted rather than the GradioUI being bugged? There's bugs that make the UI unresponsive in a few places

**Comment by Vedant-CTOI** [comment]
Thanks for responding. I keep getting 'math domain error' no matter wherever I keep the file.

**Comment by ItsGeneralButtNaked** [comment]
Ah Ive not seen that error. I think we have to just wait a while as the UI is pretty borked unfortunately.

I really like this all in one approach to the UI but maybe it'd be easier to manage if things were separated a little.

**Comment by Helikaon23s** [comment]
I got that error when it couldn't find any or just 1 file in a folder I gave it. 

At the moment, I'm using an older version from 2 days ago that works , when I updated yesterday everything in the making loras section started erroring when I pressed buttons . As noted above, it's borked.

**Comment by Vedant-CTOI** [comment]
> I got that error when it couldn't find any or just 1 file in a folder I gave it.
> 
> At the moment, I'm using an older version from 2 days ago that works , when I updated yesterday everything in the making loras section started erroring when I pressed buttons . As noted above, it's borked.

Yes, this was it. My folder had 1 file only. It worked the moment I increased the number of files in the audio directory. Thanks a million tonnes for this tip. I read through Tutorial.md and every resource to check what am I doing wrong! Thanks again.
